#!/bin/bash
set -e
#set -x

needhelp(){
  echo ''
  echo 'Usage:'
  echo ' sh tool.sh [command] [serviceName]  [args]'
  echo ''
  echo 'Detail:'
  echo ' Command                Des                                      eg.
 init                   init env                                 ./ase init
 new                    new app                                  ./ase new {myapp}
 config                 generate internal proto                  ./ase config {myapp}
 api                    generate all api proto                   ./ase api {myapp}
 add                    add api demo proto                       ./ase add {myapp} {myapi}
 apiclient              generate one api proto file              ./ase apiclient {myapp} {myapi}
 apiserver              generate one service file                ./ase apiserver {myapp} {myapi}
 apicommon              generate api common file                 ./ase apicommon
 apierror               generate api error file                  ./ase apierror
 buildlocal             build for local system                   ./ase buildlocal {myapp}
 buildlinux             build for linux                          ./ase buildlinux {myapp}
 deploydev              deploy for dev                           ./ase deploydev {myapp}
 generate               generate                                 ./ase generate {myapp}
 all                    generate all                             ./ase all {myapp}
 start                  start service                            ./ase start {myapp}
 help                   show help                                ./ase help
  '
}

if [ $# -lt 1 ]; then
  needhelp
  exit
fi

GOHOSTOS=`go env GOHOSTOS`
GOPATH=`go env GOPATH`
VERSION=`git describe --tags --always`

cmd=$1
serviceName=$2
arg=$3

init(){
  go mod download
  go install google.golang.org/protobuf/cmd/protoc-gen-go
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
	go install github.com/go-kratos/kratos/cmd/kratos/v2
	go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2
	go install github.com/google/gnostic/cmd/protoc-gen-openapi
	go install github.com/envoyproxy/protoc-gen-validate
	go install github.com/google/wire/cmd/wire

}

new(){
  kratos new app/${serviceName} --nomod -r https://gitee.com/go-kratos/kratos-layout.git
}

config(){
  INTERNAL_PROTO_FILES=`find ./app/${serviceName}/internal -name "*.proto"`
  protoc --proto_path=./app/${serviceName}/internal \
	       --proto_path=./third_party \
 	       --go_out=paths=source_relative:./app/${serviceName}/internal \
	       ${INTERNAL_PROTO_FILES}
}

api(){
  API_PROTO_FILES=`find ./api/${serviceName} -name "*.proto"`
  protoc --proto_path=. \
         --proto_path=./api \
	       --proto_path=./third_party \
 	       --go_out=paths=source_relative:. \
 	       --go-http_out=paths=source_relative:. \
 	       --go-grpc_out=paths=source_relative:. \
 	       --openapi_out=fq_schema_naming=true,default_response=false:./doc \
	       ${API_PROTO_FILES}
}

buildlocal(){
  mkdir -p ./bin && go build -ldflags "-X main.Version=${VERSION}" -o ./bin/${serviceName} ./app/${serviceName}/cmd/${serviceName}/main.go ./app/${serviceName}/cmd/${serviceName}/wire_gen.go
}

buildlinux(){
  mkdir -p ./bin && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${VERSION}" -o ./bin/${serviceName} ./app/${serviceName}/cmd/${serviceName}/main.go ./app/${serviceName}/cmd/${serviceName}/wire_gen.go
}

deploydev(){
  scp ./bin/${serviceName} root@10.189.224.86:/home/appuser/
}

generate(){
#  go mod tidy
#	go get github.com/google/wire/cmd/wire
#	go generate ./app/${serviceName}/...
  cd ./app/${serviceName}/cmd/${serviceName}
  wire
}

start(){
  cd ./app/${serviceName}/cmd/${serviceName}/
  go run main.go wire_gen.go
}

add(){
  kratos proto add api/${serviceName}/v1/${arg}.proto
}

apiclient(){
  protoc --proto_path=. \
         --proto_path=./api \
	       --proto_path=./third_party \
 	       --go_out=paths=source_relative:. \
 	       --validate_out="lang=go:../" \
 	       --go-http_out=paths=source_relative:. \
 	       --go-grpc_out=paths=source_relative:. \
 	       --openapi_out=fq_schema_naming=true,default_response=false:./doc \
	       api/${serviceName}/v1/${arg}.proto
}

apiserver(){
  kratos proto server api/${serviceName}/v1/${arg}.proto -t app/${serviceName}/internal/service
}

apicommon(){
  protoc --proto_path=. \
         --proto_path=./api \
	       --proto_path=./third_party \
 	       --go_out=paths=source_relative:. \
         api/common/common.proto
}

apierror(){
  protoc --proto_path=. \
         --proto_path=./third_party \
         --go_out=paths=source_relative:. \
         --go-errors_out=paths=source_relative:. \
         api/error/error.proto
}


case ${cmd} in
  (init)
    init
    exit
    ;;
  (new)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    new
    exit
    ;;
  (config)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    config
    exit
    ;;
  (api)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    api
    exit
    ;;
  (buildlocal)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    buildlocal
    exit
    ;;
  (buildlinux)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    buildlinux
    exit
    ;;
  (deploydev)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    buildlinux
    deploydev
    exit
    ;;
  (generate)
    if [ $# -ne 2 ]; then
      echo "args -ne {2} , faild"
      exit
    fi
    generate
    exit
    ;;
  (start)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    start
    exit
    ;;
  (add)
    if [ $# -ne 3 ]; then
      echo "args {3} not found"
      exit
    fi
    add
    exit
    ;;
  (apiclient)
    if [ $# -ne 3 ]; then
      echo "args {3} not found"
      exit
    fi
    apiclient
    exit
    ;;
  (apiserver)
    if [ $# -ne 3 ]; then
      echo "args {3} not found"
      exit
    fi
    apiserver
    exit
    ;;
  (apicommon)
    apicommon
    exit
    ;;
  (apierror)
    apierror
    exit
    ;;
  (all)
    if [ $# -ne 2 ]; then
      echo "args {2} not found"
      exit
    fi
    init
    api
    config
    generate
    exit
    ;;
  (*)
    needhelp
    exit
    ;;
esac