server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    dsn: root:caidaoninb@tcp(127.0.0.1:33306)/todo?charset=utf8mb4&parseTime=True&loc=Local
    active: 20
    idle: 10
#    idleTimeout: 4h
#    queryTimeout: 20000ms
#    execTimeout: 20000ms
#    tranTimeout: 20000ms
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
